spring:
  application:
    name: data-generator-api

  datasource:
    url: jdbc:postgresql://localhost:5432/data_generator_db
    username: data_generator_user
    password: data_generator_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: data_generator
        format_sql: true
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    schemas: data_generator
    default-schema: data_generator
    locations: classpath:db/migration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info